# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# -- trial --
_test:
    resource: "@AcmeTestBundle/Controller/TestController.php"
    type:     annotation
   # prefix:   /main
_admin:
    resource: "@AcmeTestBundle/Controller/AdminController.php"
    type:     annotation
admin_login:
    pattern:   /admin/login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
admin_login_check:
    pattern:   /admin/login_check
admin_logout:
    pattern: /admin/logout
# ----
